### ISSUE TITLE
Can't save exist main config in admin panel

### ISSUE THREAD

**Issue by VitaliyShulik** [noxonsu/anyswap-crosschain#50]
The button is not active after filled the info...

<img width="981" alt="Screen Shot 2022-06-14 at 22 10 07" src="https://user-images.githubusercontent.com/36531102/173669797-4995b856-9b89-47fa-b5ea-cadc0f77c722.png">

**Comment by NotEternal** [comment]
conditions:
- it's a storage network
- we have a Config ID and an address
- owner of the config (address from the Main config contract) is equal the app owner (from Storage) ? probably this is the reason ?

**Comment by VitaliyShulik** [comment]
> owner of the config (address from the Main config contract) is equal the app owner (from Storage) ? probably this is the reason ?

There are no check requests for this when info about the main config is filled into these inputs.

**Comment by VitaliyShulik** [comment]
@NotEternal I tried to add the main config (owner is connected Metamask account) manually, but the button is still disabled and there is no any request to check the owner of the main config in the Network section of dev tools...

**Comment by VitaliyShulik** [comment]
Apparently, it happened 'cause the infuraID was not working...
