### ISSUE TITLE
Config contract

### ISSUE THREAD

**Issue by NotEternal** [noxonsu/anyswap-crosschain#55]
Check and add (if we don't have) methods to remove routers and tokens from the config.

**Comment by VitaliyShulik** [comment]
@NotEternal @noxonsu  есть возможность поменять роутер, просто установив новый, нет такого метода, который удаляет роутеры, если нужно будет, то можно просто удалять chainID (но это когда нужно нам или клиентам слелаем), а удаление токена с конфига сделал...
